config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :watches do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :bookings, only: [:destroy]
  patch '/accept', to: 'bookings#accept', as: :accept
  patch '/reject', to: 'bookings#reject', as: :reject
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :watch
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :watches
  has_many :bookings
end

app/models/watch.rb
class Watch < ApplicationRecord
  belongs_to :user
  validates :brand, :model, :year, presence: true
  has_many_attached :photos

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :user_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :user_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
  end

  def new
    @watch = Watch.find(params[:watch_id])
    @booking = Booking.new
    @booking.watch = @watch
  end

  def create
    @watch = Watch.find(params[:watch_id])
    @booking = Booking.new(booking_params)
    @booking.watch = @watch
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path, notice: "You have now booked the watch"
    else
      render :new
    end
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.status = "approved"
    @booking.save
    redirect_to bookings_path
  end

  def reject
    @booking = Booking.find(params[:id])
    @booking.status = "rejected"
    @booking.save
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:user_id, :watch_id, :start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @watches = Watch.all
  end
end

app/controllers/watches_controller.rb
class WatchesController < ApplicationController
  def index
    if params[:query].present?
      sql_query = " \
        watches.brand @@ :query \
        OR watches.model @@ :query \
        OR watches.address @@ :query \
        OR watches.description @@ :query \
      "
      @watches = Watch.where(sql_query, query: "%#{params[:query]}%")
   
    else
      @watches = Watch.all
    end

    @markers = @watches.geocoded.map do |watch|
      {
        lat: watch.latitude,
        lng: watch.longitude,
        info_window: render_to_string(partial: "info_window", locals: { watch: watch })
      }
    end
  end

  def show
    @booking = Booking.new
    @watch = Watch.find(params[:id])
  end

  def new
    @watch = Watch.new
  end

  def create
    @watch = Watch.new(watch_params)
    @watch.user = current_user
    if @watch.save
      redirect_to watch_path(@watch)
    else
      render :new
    end
  end

  def watch_params
    params.require(:watch).permit(:model, :year, :brand, :description, :address, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<% @host = current_user.watches.any?
   @rentings = current_user.bookings
      if @host
        @my_watches = current_user.watches
        @my_bookings = Booking.where(watch_id: @my_watches.pluck(:id))
      end
%>
<div class='dashboard-container'>
  <div class='row justify-content-center'>
    <div class="bookings">
      <h1 ml-5>My bookings:
        <%  @my_bookings.each do |booking| %>
          <%= link_to watch_path(booking.watch) do %>
            <div class="card-trip mt-1 mb-2">
              <%= cl_image_tag booking.watch.photos.last.key %>
              <div class="card-trip-infos">
                <div>
                  <h2><%= booking.watch.brand %></h2>
                  <p><em><%= booking.watch.model %></em></p>
                  <p><em><%= booking.status %></em></p>
                </div>
                <h2 class="card-trip-pricing"><%= booking.watch.year %></h2>
              </div>
            </div>
          <% end %>
          <div class='row justify-content-center'>
            <%= link_to "Accept", accept_path(id:booking.id ), method: :patch, class: "btn-success dash-button mr-4" %>
            <%= link_to "Reject", reject_path(id:booking.id ), method: :patch, class: "btn-danger dash-button ml-4"  %>
          </div>
        <% end %>
      </h1>
    </div>
    <div class="watches">
      <h1>My watches:
        <%  @my_watches.each do |watch| %>
          <%= link_to watch_path(watch) do %>
            <div class="card-trip mt-2 mb-5">
              <%= cl_image_tag watch.photos.last.key %>
              <div class="card-trip-infos">
                <div>
                  <h2><%= watch.brand %></h2>
                  <p><em><%= watch.model %></em></p>
                </div>
                <h2 class="card-trip-pricing"><%= watch.year %></h2>
              </div>
            </div>
          <% end %>
        <% end %>
      </h1>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class='row justify-content-center'>
  <div class='col-4' >
    <div class="booking-form">
      <%= simple_form_for [@watch, @booking] do |f| %>
        <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.button :submit, class: 'btn-dark' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Watchly</title>
    <%= stylesheet_pack_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Sorts+Mill+Goudy:ital@1&display=swap" rel="stylesheet">
  </head>
  <body>
  <div class="main-container">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </div>
  </body>
</html>

app/views/pages/home.html.erb
<div>
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <div class='festina carousel-img'></div>
        <div class='carousel-caption'>
          <% if user_signed_in? %>
            <h1 id='page-text' class='display-2'>Time-Share</h1>
            <h3 id='page-text'>Review our fine collection of luxury watches for every style!</h3>
          <% else %>
            <h1 id='page-text' class='display-2'>Time-Share</h1>
            <h3 id='page-text'>Luxury watches for every style!</h3>
            <%= link_to '<button type="button" class="btn btn-outline-light btn-lg">Sign up</button>'.html_safe, new_user_registration_path %>
          <% end %>
        </div>
      </div>
      <div class="carousel-item">
        <div class='breitling carousel-img'></div>
      </div>
      <div class="carousel-item">
        <div class='roger-dubois carousel-img'></div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <div>
    <h2 class="recently-added text-center">Recently added:</h2>
  </div>
  <div class='last-three mt-4'>
    <div class="container">
      <div class="cards">
        <%  @watches.last(3).each do |watch| %>
          <%= link_to watch_path(watch) do %>
            <div class="card-trip">
              <% if watch.photos.attached? %>
                <%= cl_image_tag watch.photos.last.key %>
              <% end %>
              <div class="card-trip-infos">
                <div>
                  <h2><%= watch.brand %></h2>
                  <p><em><%= watch.model %></em></p>
                </div>
                <h2 class="card-trip-pricing"><%= watch.year %></h2>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
  
<div class="footer">
  <div class="footer-copyright mt-4">
    <h5 class="company-name font-weight-bold mb-0">Time-Share, AB</h5>
    <p class='mb-0'>Drottninggatan</p>
    <p class='mb-0'>111 51 Stockholm</p>
    <p class='mb-0'>Tel: 010-127 1313</p>
  </div>
  <div>
    <%# <div class='time-share footer-logo'></div> %>
    <%= image_tag 'TimeShare.png', {:style => "width:100px;", :class => "footer-logo"}  %>
    <% link_to root_path  %>
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-lewagon fixed-top">
    <div class='navbar-logo'><%= image_tag "TimeShare.png" %></div>
  <%= form_tag watches_path, class:'form-inline', method: :get do %>
    <%= text_field_tag :query,
    params[:query],
    class: "form-control search-field",
    placeholder: "Find a watch"
  %>
    <%= submit_tag "Search", class: "btn btn-watchly btn-search" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item nav-link-w">
          <%= link_to "Add a watch", new_watch_path, class: "nav-link" %>
        </li>
        <li class="nav-item nav-link-w">
          <%= link_to "Browse Watches", watches_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "default-avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My dashboard", bookings_path, class: "dropdown-item" %>
            <%#= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/watches/_info_window.html.erb
<h2><%= link_to watch.brand, watch_path(watch)  %></h2>
<h4><%= watch.model %></h4>
<p><%= watch.address %></p>

app/views/watches/index.html.erb
<div class="container">
  <div id="map"
     style="width: 100%; height: 350px; margin-bottom: 20px; margin-top: 40px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  <div class="cards">
    <%  @watches.each do |watch| %>
      <%= link_to watch_path(watch) do %>
        <div class="card-trip">
          <% if watch.photos.attached? %>
            <%= cl_image_tag watch.photos.last.key %>
          <% end %>
          <div class="card-trip-infos">
            <div>
              <h2><%= watch.brand %></h2>
              <p><em><%= watch.model %></em></p>
            </div>
            <h2 class="card-trip-pricing"><%= watch.year %></h2>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/watches/new.html.erb
<div class="special-container">
  <div class="form-height">
    <div class="form-img">
      <div>
      <div class="form-text">
         <h4><em>More than just a watch</em></h4>
        <p>Be in time with style</p>
        </div>
      </div>
    </div>
    <div class="form-container">
      <%= simple_form_for @watch do |f| %>
        <%= f.input :brand %>
        <%= f.input :model %>
        <%= f.input :year %>
        <%= f.input :description %>
        <%= f.input :address %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <div class='row justify-content-center'>
          <%= f.submit 'Add a watch', class: 'btn btn-watchly w-100' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/watches/show.html.erb
<div class="card-box container">
  <div class="card-trip-show">
    <%= cl_image_tag @watch.photos.last.key %>
    <div class="card-trip-infos">
      <div>
        <h4><%= @watch.brand %></h4>
        <h2><%= @watch.model %></h2>
        <h6><%= @watch.year %></h6>
        <p><%= @watch.description %></p>
      </div>
      <h2 class="card-trip-pricing">€<%= @watch.price %></h2>
      <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
    </div>
    <%= simple_form_for [@watch, @booking] do |f| %>
      <div class="booking-form p-3">
        <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker start-date-left"} %>
        <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      </div>
      <%= f.button :submit, class: 'btn-dark booking-btn w-100' %>
    <% end %>
  </div>
</div>